/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessageRouteImport } from './routes/message'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreatePostRouteImport } from './routes/create-post'
import { Route as AvailableTutorRouteImport } from './routes/available-tutor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizQuickPracticeRouteImport } from './routes/quiz.quick-practice'
import { Route as QuizQuestionBankRouteImport } from './routes/quiz.question-bank'
import { Route as QuizProgressRouteImport } from './routes/quiz.progress'
import { Route as QuizMockTestRouteImport } from './routes/quiz.mock-test'
import { Route as QuizLeaderboardRouteImport } from './routes/quiz.leaderboard'
import { Route as QuizFavoritesRouteImport } from './routes/quiz.favorites'
import { Route as QuizAiSolverRouteImport } from './routes/quiz.ai-solver'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as MessageRequestsRouteImport } from './routes/message.requests'
import { Route as MessageThreadIdRouteImport } from './routes/message.$threadId'
import { Route as QuizWrittenSubjectIdRouteImport } from './routes/quiz.written.$subjectId'
import { Route as QuizSubjectSubjectIdRouteImport } from './routes/quiz.subject.$subjectId'
import { Route as QuizMockTestTestIdRouteImport } from './routes/quiz.mock-test_.$testId'
import { Route as QuizExamSubjectIdRouteImport } from './routes/quiz.exam.$subjectId'
import { Route as QuizCqSubjectIdRouteImport } from './routes/quiz.cq.$subjectId'
import { Route as QuizBoardBoardIdRouteImport } from './routes/quiz.board.$boardId'
import { Route as MessageRequestRequestIdRouteImport } from './routes/message.request.$requestId'
import { Route as QuizSubjectSubjectIdCategoryRouteImport } from './routes/quiz.subject.$subjectId_.$category'
import { Route as QuizMockTestCategoryCategoryIdRouteImport } from './routes/quiz.mock-test_.category.$categoryId'
import { Route as QuizMockTestTestIdRunRouteImport } from './routes/quiz.mock-test_.$testId_.run'
import { Route as QuizSubjectSubjectIdCategoryChapterIdRouteImport } from './routes/quiz.subject.$subjectId_.$category_.$chapterId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePostRoute = CreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailableTutorRoute = AvailableTutorRouteImport.update({
  id: '/available-tutor',
  path: '/available-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizRoute,
} as any)
const QuizQuickPracticeRoute = QuizQuickPracticeRouteImport.update({
  id: '/quick-practice',
  path: '/quick-practice',
  getParentRoute: () => QuizRoute,
} as any)
const QuizQuestionBankRoute = QuizQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => QuizRoute,
} as any)
const QuizProgressRoute = QuizProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => QuizRoute,
} as any)
const QuizMockTestRoute = QuizMockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => QuizRoute,
} as any)
const QuizLeaderboardRoute = QuizLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => QuizRoute,
} as any)
const QuizFavoritesRoute = QuizFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => QuizRoute,
} as any)
const QuizAiSolverRoute = QuizAiSolverRouteImport.update({
  id: '/ai-solver',
  path: '/ai-solver',
  getParentRoute: () => QuizRoute,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRequestsRoute = MessageRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => MessageRoute,
} as any)
const MessageThreadIdRoute = MessageThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MessageRoute,
} as any)
const QuizWrittenSubjectIdRoute = QuizWrittenSubjectIdRouteImport.update({
  id: '/written/$subjectId',
  path: '/written/$subjectId',
  getParentRoute: () => QuizRoute,
} as any)
const QuizSubjectSubjectIdRoute = QuizSubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => QuizRoute,
} as any)
const QuizMockTestTestIdRoute = QuizMockTestTestIdRouteImport.update({
  id: '/mock-test_/$testId',
  path: '/mock-test/$testId',
  getParentRoute: () => QuizRoute,
} as any)
const QuizExamSubjectIdRoute = QuizExamSubjectIdRouteImport.update({
  id: '/exam/$subjectId',
  path: '/exam/$subjectId',
  getParentRoute: () => QuizRoute,
} as any)
const QuizCqSubjectIdRoute = QuizCqSubjectIdRouteImport.update({
  id: '/cq/$subjectId',
  path: '/cq/$subjectId',
  getParentRoute: () => QuizRoute,
} as any)
const QuizBoardBoardIdRoute = QuizBoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => QuizRoute,
} as any)
const MessageRequestRequestIdRoute = MessageRequestRequestIdRouteImport.update({
  id: '/request/$requestId',
  path: '/request/$requestId',
  getParentRoute: () => MessageRoute,
} as any)
const QuizSubjectSubjectIdCategoryRoute =
  QuizSubjectSubjectIdCategoryRouteImport.update({
    id: '/subject/$subjectId_/$category',
    path: '/subject/$subjectId/$category',
    getParentRoute: () => QuizRoute,
  } as any)
const QuizMockTestCategoryCategoryIdRoute =
  QuizMockTestCategoryCategoryIdRouteImport.update({
    id: '/mock-test_/category/$categoryId',
    path: '/mock-test/category/$categoryId',
    getParentRoute: () => QuizRoute,
  } as any)
const QuizMockTestTestIdRunRoute = QuizMockTestTestIdRunRouteImport.update({
  id: '/mock-test_/$testId_/run',
  path: '/mock-test/$testId/run',
  getParentRoute: () => QuizRoute,
} as any)
const QuizSubjectSubjectIdCategoryChapterIdRoute =
  QuizSubjectSubjectIdCategoryChapterIdRouteImport.update({
    id: '/subject/$subjectId_/$category_/$chapterId',
    path: '/subject/$subjectId/$category/$chapterId',
    getParentRoute: () => QuizRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/available-tutor': typeof AvailableTutorRoute
  '/create-post': typeof CreatePostRoute
  '/login': typeof LoginRoute
  '/message': typeof MessageRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRouteWithChildren
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/message/$threadId': typeof MessageThreadIdRoute
  '/message/requests': typeof MessageRequestsRoute
  '/post/$postId': typeof PostPostIdRoute
  '/quiz/ai-solver': typeof QuizAiSolverRoute
  '/quiz/favorites': typeof QuizFavoritesRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/mock-test': typeof QuizMockTestRoute
  '/quiz/progress': typeof QuizProgressRoute
  '/quiz/question-bank': typeof QuizQuestionBankRoute
  '/quiz/quick-practice': typeof QuizQuickPracticeRoute
  '/quiz/': typeof QuizIndexRoute
  '/message/request/$requestId': typeof MessageRequestRequestIdRoute
  '/quiz/board/$boardId': typeof QuizBoardBoardIdRoute
  '/quiz/cq/$subjectId': typeof QuizCqSubjectIdRoute
  '/quiz/exam/$subjectId': typeof QuizExamSubjectIdRoute
  '/quiz/mock-test/$testId': typeof QuizMockTestTestIdRoute
  '/quiz/subject/$subjectId': typeof QuizSubjectSubjectIdRoute
  '/quiz/written/$subjectId': typeof QuizWrittenSubjectIdRoute
  '/quiz/mock-test/$testId/run': typeof QuizMockTestTestIdRunRoute
  '/quiz/mock-test/category/$categoryId': typeof QuizMockTestCategoryCategoryIdRoute
  '/quiz/subject/$subjectId/$category': typeof QuizSubjectSubjectIdCategoryRoute
  '/quiz/subject/$subjectId/$category/$chapterId': typeof QuizSubjectSubjectIdCategoryChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/available-tutor': typeof AvailableTutorRoute
  '/create-post': typeof CreatePostRoute
  '/login': typeof LoginRoute
  '/message': typeof MessageRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/message/$threadId': typeof MessageThreadIdRoute
  '/message/requests': typeof MessageRequestsRoute
  '/post/$postId': typeof PostPostIdRoute
  '/quiz/ai-solver': typeof QuizAiSolverRoute
  '/quiz/favorites': typeof QuizFavoritesRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/mock-test': typeof QuizMockTestRoute
  '/quiz/progress': typeof QuizProgressRoute
  '/quiz/question-bank': typeof QuizQuestionBankRoute
  '/quiz/quick-practice': typeof QuizQuickPracticeRoute
  '/quiz': typeof QuizIndexRoute
  '/message/request/$requestId': typeof MessageRequestRequestIdRoute
  '/quiz/board/$boardId': typeof QuizBoardBoardIdRoute
  '/quiz/cq/$subjectId': typeof QuizCqSubjectIdRoute
  '/quiz/exam/$subjectId': typeof QuizExamSubjectIdRoute
  '/quiz/mock-test/$testId': typeof QuizMockTestTestIdRoute
  '/quiz/subject/$subjectId': typeof QuizSubjectSubjectIdRoute
  '/quiz/written/$subjectId': typeof QuizWrittenSubjectIdRoute
  '/quiz/mock-test/$testId/run': typeof QuizMockTestTestIdRunRoute
  '/quiz/mock-test/category/$categoryId': typeof QuizMockTestCategoryCategoryIdRoute
  '/quiz/subject/$subjectId/$category': typeof QuizSubjectSubjectIdCategoryRoute
  '/quiz/subject/$subjectId/$category/$chapterId': typeof QuizSubjectSubjectIdCategoryChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/available-tutor': typeof AvailableTutorRoute
  '/create-post': typeof CreatePostRoute
  '/login': typeof LoginRoute
  '/message': typeof MessageRouteWithChildren
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRouteWithChildren
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/message/$threadId': typeof MessageThreadIdRoute
  '/message/requests': typeof MessageRequestsRoute
  '/post/$postId': typeof PostPostIdRoute
  '/quiz/ai-solver': typeof QuizAiSolverRoute
  '/quiz/favorites': typeof QuizFavoritesRoute
  '/quiz/leaderboard': typeof QuizLeaderboardRoute
  '/quiz/mock-test': typeof QuizMockTestRoute
  '/quiz/progress': typeof QuizProgressRoute
  '/quiz/question-bank': typeof QuizQuestionBankRoute
  '/quiz/quick-practice': typeof QuizQuickPracticeRoute
  '/quiz/': typeof QuizIndexRoute
  '/message/request/$requestId': typeof MessageRequestRequestIdRoute
  '/quiz/board/$boardId': typeof QuizBoardBoardIdRoute
  '/quiz/cq/$subjectId': typeof QuizCqSubjectIdRoute
  '/quiz/exam/$subjectId': typeof QuizExamSubjectIdRoute
  '/quiz/mock-test_/$testId': typeof QuizMockTestTestIdRoute
  '/quiz/subject/$subjectId': typeof QuizSubjectSubjectIdRoute
  '/quiz/written/$subjectId': typeof QuizWrittenSubjectIdRoute
  '/quiz/mock-test_/$testId_/run': typeof QuizMockTestTestIdRunRoute
  '/quiz/mock-test_/category/$categoryId': typeof QuizMockTestCategoryCategoryIdRoute
  '/quiz/subject/$subjectId_/$category': typeof QuizSubjectSubjectIdCategoryRoute
  '/quiz/subject/$subjectId_/$category_/$chapterId': typeof QuizSubjectSubjectIdCategoryChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/available-tutor'
    | '/create-post'
    | '/login'
    | '/message'
    | '/profile'
    | '/quiz'
    | '/register'
    | '/welcome'
    | '/message/$threadId'
    | '/message/requests'
    | '/post/$postId'
    | '/quiz/ai-solver'
    | '/quiz/favorites'
    | '/quiz/leaderboard'
    | '/quiz/mock-test'
    | '/quiz/progress'
    | '/quiz/question-bank'
    | '/quiz/quick-practice'
    | '/quiz/'
    | '/message/request/$requestId'
    | '/quiz/board/$boardId'
    | '/quiz/cq/$subjectId'
    | '/quiz/exam/$subjectId'
    | '/quiz/mock-test/$testId'
    | '/quiz/subject/$subjectId'
    | '/quiz/written/$subjectId'
    | '/quiz/mock-test/$testId/run'
    | '/quiz/mock-test/category/$categoryId'
    | '/quiz/subject/$subjectId/$category'
    | '/quiz/subject/$subjectId/$category/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/available-tutor'
    | '/create-post'
    | '/login'
    | '/message'
    | '/profile'
    | '/register'
    | '/welcome'
    | '/message/$threadId'
    | '/message/requests'
    | '/post/$postId'
    | '/quiz/ai-solver'
    | '/quiz/favorites'
    | '/quiz/leaderboard'
    | '/quiz/mock-test'
    | '/quiz/progress'
    | '/quiz/question-bank'
    | '/quiz/quick-practice'
    | '/quiz'
    | '/message/request/$requestId'
    | '/quiz/board/$boardId'
    | '/quiz/cq/$subjectId'
    | '/quiz/exam/$subjectId'
    | '/quiz/mock-test/$testId'
    | '/quiz/subject/$subjectId'
    | '/quiz/written/$subjectId'
    | '/quiz/mock-test/$testId/run'
    | '/quiz/mock-test/category/$categoryId'
    | '/quiz/subject/$subjectId/$category'
    | '/quiz/subject/$subjectId/$category/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/available-tutor'
    | '/create-post'
    | '/login'
    | '/message'
    | '/profile'
    | '/quiz'
    | '/register'
    | '/welcome'
    | '/message/$threadId'
    | '/message/requests'
    | '/post/$postId'
    | '/quiz/ai-solver'
    | '/quiz/favorites'
    | '/quiz/leaderboard'
    | '/quiz/mock-test'
    | '/quiz/progress'
    | '/quiz/question-bank'
    | '/quiz/quick-practice'
    | '/quiz/'
    | '/message/request/$requestId'
    | '/quiz/board/$boardId'
    | '/quiz/cq/$subjectId'
    | '/quiz/exam/$subjectId'
    | '/quiz/mock-test_/$testId'
    | '/quiz/subject/$subjectId'
    | '/quiz/written/$subjectId'
    | '/quiz/mock-test_/$testId_/run'
    | '/quiz/mock-test_/category/$categoryId'
    | '/quiz/subject/$subjectId_/$category'
    | '/quiz/subject/$subjectId_/$category_/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailableTutorRoute: typeof AvailableTutorRoute
  CreatePostRoute: typeof CreatePostRoute
  LoginRoute: typeof LoginRoute
  MessageRoute: typeof MessageRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  WelcomeRoute: typeof WelcomeRoute
  PostPostIdRoute: typeof PostPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-post': {
      id: '/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof CreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/available-tutor': {
      id: '/available-tutor'
      path: '/available-tutor'
      fullPath: '/available-tutor'
      preLoaderRoute: typeof AvailableTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/quick-practice': {
      id: '/quiz/quick-practice'
      path: '/quick-practice'
      fullPath: '/quiz/quick-practice'
      preLoaderRoute: typeof QuizQuickPracticeRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/question-bank': {
      id: '/quiz/question-bank'
      path: '/question-bank'
      fullPath: '/quiz/question-bank'
      preLoaderRoute: typeof QuizQuestionBankRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/progress': {
      id: '/quiz/progress'
      path: '/progress'
      fullPath: '/quiz/progress'
      preLoaderRoute: typeof QuizProgressRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/mock-test': {
      id: '/quiz/mock-test'
      path: '/mock-test'
      fullPath: '/quiz/mock-test'
      preLoaderRoute: typeof QuizMockTestRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/leaderboard': {
      id: '/quiz/leaderboard'
      path: '/leaderboard'
      fullPath: '/quiz/leaderboard'
      preLoaderRoute: typeof QuizLeaderboardRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/favorites': {
      id: '/quiz/favorites'
      path: '/favorites'
      fullPath: '/quiz/favorites'
      preLoaderRoute: typeof QuizFavoritesRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/ai-solver': {
      id: '/quiz/ai-solver'
      path: '/ai-solver'
      fullPath: '/quiz/ai-solver'
      preLoaderRoute: typeof QuizAiSolverRouteImport
      parentRoute: typeof QuizRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message/requests': {
      id: '/message/requests'
      path: '/requests'
      fullPath: '/message/requests'
      preLoaderRoute: typeof MessageRequestsRouteImport
      parentRoute: typeof MessageRoute
    }
    '/message/$threadId': {
      id: '/message/$threadId'
      path: '/$threadId'
      fullPath: '/message/$threadId'
      preLoaderRoute: typeof MessageThreadIdRouteImport
      parentRoute: typeof MessageRoute
    }
    '/quiz/written/$subjectId': {
      id: '/quiz/written/$subjectId'
      path: '/written/$subjectId'
      fullPath: '/quiz/written/$subjectId'
      preLoaderRoute: typeof QuizWrittenSubjectIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/subject/$subjectId': {
      id: '/quiz/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/quiz/subject/$subjectId'
      preLoaderRoute: typeof QuizSubjectSubjectIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/mock-test_/$testId': {
      id: '/quiz/mock-test_/$testId'
      path: '/mock-test/$testId'
      fullPath: '/quiz/mock-test/$testId'
      preLoaderRoute: typeof QuizMockTestTestIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/exam/$subjectId': {
      id: '/quiz/exam/$subjectId'
      path: '/exam/$subjectId'
      fullPath: '/quiz/exam/$subjectId'
      preLoaderRoute: typeof QuizExamSubjectIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/cq/$subjectId': {
      id: '/quiz/cq/$subjectId'
      path: '/cq/$subjectId'
      fullPath: '/quiz/cq/$subjectId'
      preLoaderRoute: typeof QuizCqSubjectIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/board/$boardId': {
      id: '/quiz/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/quiz/board/$boardId'
      preLoaderRoute: typeof QuizBoardBoardIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/message/request/$requestId': {
      id: '/message/request/$requestId'
      path: '/request/$requestId'
      fullPath: '/message/request/$requestId'
      preLoaderRoute: typeof MessageRequestRequestIdRouteImport
      parentRoute: typeof MessageRoute
    }
    '/quiz/subject/$subjectId_/$category': {
      id: '/quiz/subject/$subjectId_/$category'
      path: '/subject/$subjectId/$category'
      fullPath: '/quiz/subject/$subjectId/$category'
      preLoaderRoute: typeof QuizSubjectSubjectIdCategoryRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/mock-test_/category/$categoryId': {
      id: '/quiz/mock-test_/category/$categoryId'
      path: '/mock-test/category/$categoryId'
      fullPath: '/quiz/mock-test/category/$categoryId'
      preLoaderRoute: typeof QuizMockTestCategoryCategoryIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/mock-test_/$testId_/run': {
      id: '/quiz/mock-test_/$testId_/run'
      path: '/mock-test/$testId/run'
      fullPath: '/quiz/mock-test/$testId/run'
      preLoaderRoute: typeof QuizMockTestTestIdRunRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/subject/$subjectId_/$category_/$chapterId': {
      id: '/quiz/subject/$subjectId_/$category_/$chapterId'
      path: '/subject/$subjectId/$category/$chapterId'
      fullPath: '/quiz/subject/$subjectId/$category/$chapterId'
      preLoaderRoute: typeof QuizSubjectSubjectIdCategoryChapterIdRouteImport
      parentRoute: typeof QuizRoute
    }
  }
}

interface MessageRouteChildren {
  MessageThreadIdRoute: typeof MessageThreadIdRoute
  MessageRequestsRoute: typeof MessageRequestsRoute
  MessageRequestRequestIdRoute: typeof MessageRequestRequestIdRoute
}

const MessageRouteChildren: MessageRouteChildren = {
  MessageThreadIdRoute: MessageThreadIdRoute,
  MessageRequestsRoute: MessageRequestsRoute,
  MessageRequestRequestIdRoute: MessageRequestRequestIdRoute,
}

const MessageRouteWithChildren =
  MessageRoute._addFileChildren(MessageRouteChildren)

interface QuizRouteChildren {
  QuizAiSolverRoute: typeof QuizAiSolverRoute
  QuizFavoritesRoute: typeof QuizFavoritesRoute
  QuizLeaderboardRoute: typeof QuizLeaderboardRoute
  QuizMockTestRoute: typeof QuizMockTestRoute
  QuizProgressRoute: typeof QuizProgressRoute
  QuizQuestionBankRoute: typeof QuizQuestionBankRoute
  QuizQuickPracticeRoute: typeof QuizQuickPracticeRoute
  QuizIndexRoute: typeof QuizIndexRoute
  QuizBoardBoardIdRoute: typeof QuizBoardBoardIdRoute
  QuizCqSubjectIdRoute: typeof QuizCqSubjectIdRoute
  QuizExamSubjectIdRoute: typeof QuizExamSubjectIdRoute
  QuizMockTestTestIdRoute: typeof QuizMockTestTestIdRoute
  QuizSubjectSubjectIdRoute: typeof QuizSubjectSubjectIdRoute
  QuizWrittenSubjectIdRoute: typeof QuizWrittenSubjectIdRoute
  QuizMockTestTestIdRunRoute: typeof QuizMockTestTestIdRunRoute
  QuizMockTestCategoryCategoryIdRoute: typeof QuizMockTestCategoryCategoryIdRoute
  QuizSubjectSubjectIdCategoryRoute: typeof QuizSubjectSubjectIdCategoryRoute
  QuizSubjectSubjectIdCategoryChapterIdRoute: typeof QuizSubjectSubjectIdCategoryChapterIdRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizAiSolverRoute: QuizAiSolverRoute,
  QuizFavoritesRoute: QuizFavoritesRoute,
  QuizLeaderboardRoute: QuizLeaderboardRoute,
  QuizMockTestRoute: QuizMockTestRoute,
  QuizProgressRoute: QuizProgressRoute,
  QuizQuestionBankRoute: QuizQuestionBankRoute,
  QuizQuickPracticeRoute: QuizQuickPracticeRoute,
  QuizIndexRoute: QuizIndexRoute,
  QuizBoardBoardIdRoute: QuizBoardBoardIdRoute,
  QuizCqSubjectIdRoute: QuizCqSubjectIdRoute,
  QuizExamSubjectIdRoute: QuizExamSubjectIdRoute,
  QuizMockTestTestIdRoute: QuizMockTestTestIdRoute,
  QuizSubjectSubjectIdRoute: QuizSubjectSubjectIdRoute,
  QuizWrittenSubjectIdRoute: QuizWrittenSubjectIdRoute,
  QuizMockTestTestIdRunRoute: QuizMockTestTestIdRunRoute,
  QuizMockTestCategoryCategoryIdRoute: QuizMockTestCategoryCategoryIdRoute,
  QuizSubjectSubjectIdCategoryRoute: QuizSubjectSubjectIdCategoryRoute,
  QuizSubjectSubjectIdCategoryChapterIdRoute:
    QuizSubjectSubjectIdCategoryChapterIdRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailableTutorRoute: AvailableTutorRoute,
  CreatePostRoute: CreatePostRoute,
  LoginRoute: LoginRoute,
  MessageRoute: MessageRouteWithChildren,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRouteWithChildren,
  RegisterRoute: RegisterRoute,
  WelcomeRoute: WelcomeRoute,
  PostPostIdRoute: PostPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
